[tools]
bat = "latest"
ffmpeg = "latest"
gh = "latest"
lazydocker = "latest"
lazygit = "latest"
lnav = "latest"
neovim = "latest"
node = "lts"
python = "3"
ripgrep = "latest"
ruby = "3"
rust = "latest"
starship = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "python"]

[settings.ruby]
default_packages_file = "~/.config/mise/.default-gems"

[settings.python]
uv_venv_auto = true
uv_venv_create_args = ['--seed']

